# Generated by Django 4.1.2 on 2022-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(to='animals.tags'),
        ),
    ]
