# Generated by Django 4.1.2 on 2022-10-30 09:21

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_tags_animal_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_URLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_URL', models.FilePathField(max_length=256, null=True, path=animals.models.images_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='pic_URL',
        ),
        migrations.AddField(
            model_name='animal',
            name='pictures',
            field=models.ManyToManyField(to='animals.picture_urls'),
        ),
    ]
