# Generated by Django 4.1.2 on 2022-10-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_picture_urls_remove_animal_pic_url_animal_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_urls',
            name='picture_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture_urls',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='animals.picture_urls'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='animals.tags'),
        ),
    ]
